; PLAYLIST
; https://www.youtube.com/watch?v=O4IgYgnT6qU&list=PLrIwy5Fq_HiPDD1T_LTHX8yuuCxKI4vcm

	.ORG 0000H  ; RECOMMENDED ADDRESS FOR THE SIMULATOR

; 1. LOADING NUMBERS INTO MAIN REGISTERS (2 BYTES USED)
     ; Playlist with link '&index=1' (youtube at @time 16:38)
	LD A,10		; NUMBER WITHOUT H OR B IS A DECIMAL
			    ; 0AH LOADED INTO A, THE ACCUMULATOR
	LD B,33H	; HEX NUMBER
	LD D,10001111B	; 10001111, 8F IN HEX OR 143 IN DECIMAL
	LD D,0ABH

; 2. COPYING CONTENT OF REGISTERS (EVERY COPY TAKES 2 BYTES)
     ; Playlist with link '&index=2' (youtube at @time 01:13)
	LD E,A		; ALSO WITH LD COMMAND FOR EVERY 8-BIT REGISTER
	LD H,B
	LD L,D
	LD H,H      ; ALL EXACTLY THE SAME AS THE INTEL

; LOADING 2 REGISTERS AT ONCE (SAVES 1 BYTE => 3 INSTEAD OF 2*2 BYTES)
  ; Playlist with link '&index=2' (youtube at @time 04:42)
	LD BC,1234H
	LD DE,5678H
	LD HL,9ABCH
	LD SP,1234H	; YOU CAN ALSO LOAD TO THE STACK POINTER (SP)
	LD IX,1234H	; YOU CAN EVEN LOAD TO IX REGISTER
	LD IY,1234H	; ABD IY REGISTER

; STORE AND LOAD ACCUMULATOR TO/FROM A MEMORY ADDRESS
  ; Playlist with link '&index=2' (youtube at @time 07:42)
        LD A,12H
	LD (010AH),A
	LD A,0H 	 ; SET A TO 0 TO SEE LOADING BACK FROM MEMORY
	LD A,(010AH) ; CHECK WITH MEMORY EDITOR WHAT IS GOING ON

; TO SAVE REGISTER B TO STORAGE 0100H FOR EXAMPLE
  ; Playlist with link '&index=2' (youtube at @time 11:36)
	LD HL,0100H	; IF REGISTER HL IS FREE YOU CAN USE HL
			    ; AS A DATA POINTER TO MEMORY
	LD B,56H	; B FOR EXAMPLE HAS VALUE 56H
	LD (HL),B	; COPY TO THE MEMORY, REPRESENTED BY HL
	LD C,(HL)	; EXAMPLE LOAD C FROM THE MEMORY
	LD (HL),78H	; ALSO YOU CAN DIRECTLY ADD VALUE TO THE MEMORY

	LD IX,0110H	; ALSO POSSIBLE WITH IX AS DATA POINTER
	LD B,66H	; B FOR EXAMPLE HAS 66H
	LD (IX+1),B	; COPY TO THE MEMORY. WITH IX YOU HAVE TO
			    ; SPECIFY INDEX FROM 0 TO +127 OR -128
			    ; SO IN THIS EXAMPLE SAVED TO 0111H
	LD C,(IX+1)	; EXAMPLE LOAD C FROM THE MEMORY
	LD (IX-1),74H	; ALSO YOU CAN DIRECTLY ADD VALUE TO THE MEMORY

	LD IY,0120H	; EXAMPLE WITH IY AS DATA POINTER
	LD B,76H	; B FOR EXAMPLE HAS 76H
	LD (IY+0),B	; COPY TO THE MEMORY 0120
	LD C,(IY+0)	; EXAMPLE LOAD C FROM THE MEMORY
	LD (IY+10),80H	; ALSO YOU CAN DIRECTLY ADD VALUE TO THE MEMORY
			        ; IY POINTER 0120 +10 => 012A

; 3. ANOTHER WAY TO LOAD & STORE THE ACCUMULATOR WITH PAIR OF REGISTERS
     ; Playlist with link '&index=3' (youtube at @time 02:57 )
	LD A,12H	; LD VALUE 12H INTO REGISTER A (THE ACCUMULATOR)
	LD BC,0100H	; LOAD REGISTERS BC WITH ADDRESS 0100H
	LD DE,0110H	; LOAD REGISTERS DE WITH ADDRESS 0110H
	LD (BC),A	; STORE ACCUMULATOR IN ADDRESS OF REGISTERS BC
	LD A,20H	; CHANCE REGISTER A
	LD (DE),A	; STORE VALUE OF A NOW IN ADDRESS OF DE
	LD A,(BC)
	LD A,(DE)

; 4. SAVING A 16-BIT VALUE
     ; Playlist with link '&index=3' (youtube at @time 06:47)
     ; SAME POSSIBLE WITH REGISTERS PAIRS BC, DE, HL, IX, IY AND EVEN SP
	LD HL,1234h
	LD (0100H),HL
	LD HL,(0100H)

	LD IY,2345h
	LD (0110H),IY
	LD IY,(0110H)

	HALT


; Z80 RELEASED IN 1976 - 8 500 TRANSISTORS - CLOCK SPEED 2.5 TO 10 MHZ
; CMOS VERSION 20 MHZ - OPERATING VOLTAGE +5V - 40-PIN DIP CASE

; DECIMAL SYSTEM 10 DIGITS FROM 0 TO 9
;        10^4   10^3  10^2 10^1 10^0
; ... 10000   1000   100   10    1

; BINARY SYSTEM 2 DIGITS FROM 0 TO 1
;       2^7  2^6  2^5  2^4 2^3 2^2 2^1 2^0    8 BITS OR 1 BYTE
;     128  +64  +32  +16  +8  +4  +2  +1    = 255 (0...255)

; STATES 0 AND 1 MEANS -128 TO +127:    2^8 = 256