; PLAYLIST
; https://www.youtube.com/watch?v=Oc2C6EvV4A4&list=PLrIwy5Fq_HiPDD1T_LTHX8yuuCxKI4vcm&index=4
; use memory editor window to check the values

	.ORG 0000H  ; RECOMMENDED ADDRESS FOR THE SIMULATOR

; THE STACK POINTER (SP) IS JUST A REFERENCE IN MEMORY    
	LD SP,8000H	; STACK POINTER IS SET TO ADDRESS 8000
	LD HL,00FFH	; SETTING THE HL REGISTER
	LD SP,HL

	;ANOTHER WAY TO SET THE VALUE (WITH MEMORY ADDRESS)
	CALL INITVAL1	; SET SOME VALUE FOR DEMO, CHECK MEMORY EDITOR!

	LD SP,(00F0H)	; LOADING THE VALUE OF ADDRESS 00F0 INTO
			; THE STACK POINTER

	LD IX,1234H
	LD SP,IX	; STACK POINTER CAN ALSO BE SET WITH VALUE OF IX
	LD IY,5678H
	LD SP,IY	; OR IY

	LD (00F0H),SP	; SAVE THE STACK POINTER, SEE MEMORY EDITOR
			; LOW BYTE FOLLOWED BY HIGH BYTE

; STACK POINTER IS USED TO KEEP RETURN ADDRESSES FROM CALL COMMANDS
; OR BY INTERRUPTS AND ALSO TO SAVE THE CPU REGISTERS

; USE PUSH AND POP TO SAVE REGISTER VALUES AND GET THEM BACK WHEN NEEDED
	LD SP,00FFH	; STACK POINTER SET TO ADDRESS FF
	LD BC,5678H
	LD DE,9ABCH
	LD HL,1234H
	LD A,12H

	PUSH AF		; PUSH TO SAVE (A-FLAG)
	PUSH BC
	PUSH DE
	PUSH HL

	LD BC,FFFFH	; SET ALL REGISTERS TO FF TO CHECK WHEN
	LD DE,FFFFH	; RETRIEVING BACK
	LD HL,FFFFH
	LD A, FFH

	POP HL		; TO RETREIVE BACK, POP IN REVERSE ORDER
	POP DE
	POP BC
	POP AF

; EX COMMAND TO EXCHANGE VALUES INSIDE MAIN REGISTERS
	LD DE,1234H
	LD HL,5678H
	EX DE,HL	; EXCHANGING VALUES BETWEEN REGISTERS
	EX DE,HL	; AGAIN JUST TO SET BACK IN THIS EXAMPLE


; EXX COMMAND TO MIRROR SWITCH BETWEEN MAIN AND ALTERNATE REGISTERS
	LD A,0ABH
	AND A		 ; AND IS JUST TO CHANGE THE MAIN FLAG REGISTER
			     ; IF A AND A' NEEDED TO SWITCH ALSO
	LD BC,9ABCH
	LD DE,1234H
	LD HL,5678H
	EXX		     ; EXCHANGING ALL VALUES BETWEEN MAIN AND
			     ; ALTERNATE REGISTERS WITH EXCEPTION OF A A'

	EX AF,AF'	 ; IF A AND A' NEEDED TO SWITCH ALSO
	EX AF,AF'
	EXX		     ; AGAIN JUST TO SET BACK IN THIS EXAMPLE


	LD BC,5678H
	LD SP,0FFH
	PUSH BC
	LD HL,1234H
	EX (SP),HL
	EX (SP),IX
	EX (SP),IY
	POP BC

	HALT

; SOME DEMO VALUES IN MEMORY
INITVAL1
	LD HL,8004H	   ; CHECK THIS! H: 80 AND L: 04
	LD (00F0H),HL  ; IN MEMORY EDITOR LOW_BYTE HIGH_BYTE AT 00F0 !
	RET

END

