	.ORG 0000H  ; RECOMMENDED ADDRESS FOR THE SIMULATOR

	LD A,1
	SUB 1	; SIGN FLAGS IS ZERO BECAUSE STILL POSITIVE NR.
		; ZERO FLAG IS 1 BECAUSE ACCUMUMATOR IS 0
	SUB 2	; SIGN FLAG IS 1 BECAUSE IT IS NOW A NEGATIVE NUMBER
		; CARRY FLAG IS SET BECAUSE THERE WAS AN OVERFLOW
	LD D,3
	SUB D	; A B C D E H L (HL) (IX+INDEX) (IY+INDEX)
	;CPL
	;ADD A,1
	NEG
	NEG

	; 16 BIT EXAMPLE OF SUBSTRACTION
	CALL INITVALS

	LD A,L
	SUB E
	LD L,A
	LD A,H
	SBC A,D
	; ALL SBC 8-BIT COMMANDS
	; SBC A,A SBC A,B SBC A,D SBC A,E SBC A,H SBC A,L SBC A,(HL)
	; SBC A,(IX+INDEX) SBC A,(IY+INDEX)
	; SBC VITH A VALUE=> SBC A,VALUE

	LD H,A

	; EASIER WAY
	CALL  INITVALS
	SCF	; SET CARRY FLAG
	CCF	; SET COMPLEMENT CARRY FLAG

	SBC HL,DE

	HALT

INITVALS
	LD DE,1234H
	LD HL,5678H
	RET

END

