.Z80
 TITLE 'HEXCHAR - Created by VSOFT'

;-------------------------------------------------------------------------
; CP/M Demo Program
;-------------------------------------------------------------------------

; ASCII CHARACTERS
 ESC   EQU 1BH
 CR    EQU 0DH  ; CARRIAGE RETURN
 LF    EQU 0AH  ; LINE FEED
 CTRLZ EQU 1AH  ; OPERATOR INTERRUPT

; CP/M FUNCTIONS AND ADDRESSES
 RCHAR   EQU   1 ; READ CON: INTO (A)
 WCHAR   EQU   2 ; WRITE (A) TO CON:
 CPRINTS EQU   9 ; PRINT STRING WITH $ TERMINATOR
 BDOS    EQU   5 ; SYSTEM CALL ENTRY (BDOS)

;-------------------------------------------------------------------------
; Program loads and enters at 0100h
;-------------------------------------------------------------------------
 ORG 0100H           ; START OF TRANS. PROGRAM AREA

; Main consol output routine using CPM.
; All registers unchanged

 MAIN:
     LD DE,CLS   ; Load CLS clear screen string
     LD C,CPRINTS  ; Prepare for Write clear screen string
     CALL BDOS   ; Ask system to do it

 KEYLOOP:
     LD DE,INMSG  ; Load message asking for a key to press
     LD C,CPRINTS  ; Prepare for Write the message string
     CALL BDOS   ; Ask system to do it

     LD C,RCHAR  ; Prepare for reading one character into [C].
     CALL BDOS   ; Ask system to do it

     CP 51H   ; Compare 'Q' key (code 51 in hex), sets Zero Flag
     JP Z,EXITP  ; Jump to EXITP if Zero Flag set
     CP 71H   ; Compare 'q' key (code 71 in hex), sets Zero Flag
     JP Z,EXITP  ; Jump to EXITP if Zero Flag set

     LD A,C   ; Save C into A if other key than Q or q

     PUSH AF
     PUSH BC
     PUSH DE

     LD DE,OUTMSG
     LD C,CPRINTS
     CALL BDOS

     POP DE
     POP BC
     POP AF

     LD E,C
     LD C,WCHAR  ; Character to be sent in [C].
     CALL BDOS

     LD A,C

     PUSH AF
     PUSH BC
     PUSH DE

     LD DE,HEXMSG
     LD C,CPRINTS
     CALL BDOS

     POP DE
     POP BC
     POP AF

     PUSH AF
     SRL A
     SRL A
     SRL A
     SRL A
     CALL CONHEX
     LD (HEX),A
     POP AF
     CALL CONHEX
     LD (HEX+1),A

     LD C,CPRINTS  ;WRITESTR
     LD DE,HEX
     CALL BDOS 

     JP KEYLOOP  ; Until 'Q' or 'q', stay into the loop

 CONHEX:
     AND 0FH
     ADD A,30H
     CP 3AH
     JP M,EXITP
     ADD A,7

 EXITP:
     RET
 
 CLS:
  DB 1BH,"[H",1BH,"[2J$" ; VT100 for more info see
; DB ESC,"H",ESC,"E$" ; For Amstrad PCW 8256
; https://en.wikipedia.org/wiki/ANSI_escape_code#CP/M
 
 INMSG:
  DB 'Press any key (Q or q to quit): $'

 OUTMSG:
  DB CR,LF,'You chose: $'

 HEXMSG:
  DB CR,LF,'In HEX: $'

  HEX:
  DB "00",CR,LF,CR,LF,"$" ; 2 bytes for HEX value

 END
