	.ORG 0000H  ; RECOMMENDED ADDRESS FOR THE SIMULATOR

	; LOADING DATA INTO MEMORY FOR TESTING, WATCH IT IN MEMORY EDITOR
	LD A,11
	LD (00E1H),A	; 0BH IS SAVED IN MEMORY 00E1
	LD A,3
	LD (00EFH),A	; 03H IS SAVED IN MEMORY 00EF

	LD A,1
	ADD A,3		; ADD ONLY USED TO ACCUMULATOR (A)
			; 1. THIS SETS SIGN (SF) FLAG TO 0
			;    BECAUSE THE 7TH BIT IS NOT SET
			; 2. THE PARITY OVERFLOW FLAG (PF) WORKS ONLY
			;    FOR LOGICAL OPERATIONS SO NOT USED NOW
	LD B,5
	ADD A,B		; A B C D E H L (HL)
			; THE PARITY FLAG IS NOW
	LD E,8
	ADD A,E
	ADD A,112	; SIGN FLAG (SF) IS SET TO 1
			; PARITY OVERFLOW FLAG (PF) ALSO SET TO 1
			; BECAUSE IT IS HIGHER THAN 127
	LD HL,00F0H
	ADD A,(HL)	; THE 7TH BIT IS SET SO THE SIGN FLAG IS 1
			; THE OVERFLOW FLAG IS ALSO 1 BECAUSE IT IS
			; HIGHER THEN 127

	LD IX,00E0H	; INSTEAD OF HL WE CAN USE ALSO IX OR IY
	LD IY,00EFH
	LD A,1
	ADD A,(IX+0)	; WE HAVE TO SPECIFY AN INDEX
			; 0 .. +127, -1 .. -128
	ADD A,(IY-1)

	HALT

	END

; SF: SIGN FLAG, ZF: ZERO FLAG, PF: PARITY OVERFLOW FLAG, CF: CARRY FLAG
; HF: HALF CARRY FLAG IS ONLY USED FOR BCD OPERATIONS
; NF: DECIMAL ADJUST ACCUMULATOR FLAG ALSO USED FOR BCD OPERATIONS