	.ORG 0000H

	; 1. ADD BYTE ROW (L+E AND H+D) VIA ACCUMULATOR (A)
	CALL INITVALS1

	LD A,E
	ADD A,L			; HEX: 34 + 78
	LD L,A			; AC IS RESULT FOR L

	LD A,D
	ADD A,H			; HEX: 12 + 56
	LD H,A			; 68 IS RESULT FOR H
	; THE CARRY FLAG IS NOT SET BECAUSE VALUES STILL FITS IN BYTE


	; 2. DEMO WITH VALUE OF E TOO HIGH TO FIT IN ONE BYTE
	CALL INITVALS2

	LD A,E
	ADD A,L			; HEX: F4 + 78 = 16C TOO HIGH TO FIT L
	; SO CF IS SET! YOU HAVE TO HANDLE THE '1' OF RESULT 16C
	LD L,A			; SAVE THE 6C PART
	LD A,D
	ADC A,H			; WILL HANDLE 1 OF THE CF
				; AND SET CF BACK TO 0
	; ADD WITH CARRY CAN BE USED WITH A B C D E H L
	; (HL) (IX+INDEX) (IY+INDEX)
	LD H,A

	; 3. SIMPLE WAY FOR 16 BIT WITHOUT USING A ACCUMULATOR
	CALL INITVALS2

	ADD HL,DE		; GIVES SAME RESULT AS DEMO 2
				; POSSIBLE WITH BC DE HL SP

	CALL INITVALS3

	ADD HL,BC
	ADD HL,HL		; THIS WILL JUST DOUBLE THE VALUE

	; 4. WITH STACK POINTER (SP)
	LD SP,12F4H
	LD HL,0H


	ADD HL,SP

	; BC DE EN SP IS 12F4 IN DEMO
	LD IX,0H		; START FROM 0 OR CF IS IMMEDIATLY SET
				; BECAUSE OF ACTUAL VALUE FFFF!
	ADD IX,BC		;
	ADD IX,DE		; NEVER WITH HL!
	ADD IX,SP
	ADD IX,IX		; NEVER WITH IY!
				; 2*(3*12F4) SHOULD BE 71B8

	LD IY,0H
	ADD IY,BC		; SAME FOR IY AS FOR IX
	ADD IY,DE
	ADD IY,SP
	ADD IY,IY

	; ADD WITH CARRY
	ADC HL,BC
	ADC HL,DE
	ADC HL,HL
	ADC HL,SP


	HALT

INITVALS1:
	LD DE,1234H		; DECIMAL: 4660 + 22136 = 26796
	LD HL,5678H		; OR IN HEX: 68AC
	RET

INITVALS2:
	LD DE,12F4H		; DECIMAL: 4852 + 22136 = 26988
	LD HL,5678H		; OR IN HEX: 696C
	RET

INITVALS3:
	LD BC,12F4H
	LD HL,5678H
	RET

INITCF:
	SCF			; SET CARRY FLAG
	CCF			; COMPLEMENT CARRY FLAG
	RET

END

