	.ORG 0000H  ; RECOMMENDED ADDRESS FOR THE SIMULATOR

LOOP
	IN A, (25H)	; YOU CAN ONLY USE ACCUMULATOR
	OUT (00H),A	; OUT THE INPUT TO ADDRESS 00H
	CPL		; COMPLEMENT: 0=> 1 AND 1=> 0
	OUT (31H),A	; OUT COMPLEMENT TO ADDR 31H
	CP 00H		; COMPARE OUTPUT 31H TO 0
	JR NZ,LOOP	; KEEP LOOP UNTIL 0

	LD HL,TEXT
	LD B,T_END-TEXT	; LENGTH OF TEXT (NUMBER IN B)

PR_LOOP
	LD A,(HL)	; LOADING FIRST CHARACTER FROM MEMORY ADDRESS
	OUT (20H),A	; OUTPUT TO TERMINAL 20H
	INC HL		; INCREMENT MEMORY ADDRESS
	DJNZ PR_LOOP	; DECREMENT JUMP UNTIL 0 (USING B)

	HALT

TEXT 	DB "HELLO WORLD!"	; TEXT LABEL
T_END				; TEXT END LABEL

END

; USE THE 5 PERIPHERAL DEVICES
; DEVICE 1 => I/O PORT 00H (OUT) OUT GIVES 8 LEDS
; DEVICE 2 => I/O PORT 31H (OUT)
; DEVICE 3 => I/O PORT 25H (IN)  IN GIVES 8 INPUT SWITCHES
; DEVICE 4 => I/O PORT FFH (IN)
; DEVICE 5 => I/O PORT 20H (OUTPUT TERMINAL)